version: '3.8'
services:
  bot:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017
    restart: always
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: