name: Deploy to Production Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4.1.1
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to Production
        run: |
          ssh -o "StrictHostKeyChecking=no" root@146.190.225.169 << 'EOF'

          # Update and install NGINX
          sudo apt update
          sudo apt install nginx -y

          # Configure NGINX as reverse proxy
          echo "server {
              listen 80;
              server_name api.blazenet.work;

              location / {
                  proxy_pass http://localhost:10000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }" | sudo tee /etc/nginx/sites-available/api.blazenet.work

          sudo ln -s /etc/nginx/sites-available/api.blazenet.work /etc/nginx/sites-enabled/api.blazenet.work
          sudo nginx -t
          sudo systemctl restart nginx

          # Deploy the app
          cd /home/code/blazenetworkbot
          git pull
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          npm install pm2@latest -g
          export MONGODB_URI=${{ secrets.MONGODB_URI }}
          export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          pm2 start main.py --interpreter ./venv/bin/python --name blazenetworkbot --watch
          pm2 save
          EOF