name: DB Backup every hour

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: gabrielrufino/mongodump-action@v1
        with:
          connection-string: ${{ secrets.MONGODB_URI }}
      - uses: actions/upload-artifact@v4
        with:
          name: hourly-dump
          path: ${{ github.workspace }}/dump